### ISSUE TITLE
Pass tests

### ISSUE THREAD

**Issue by lrettig** [ewasm/testnet#23]
cf. https://notes.ethereum.org/9xX4L2QyQPmzJ0Xh3RAgJA

Manually listing these here since I don't want to dump the entire tests board into the testnet board on Waffle:

- [x] Add existing test cases to the new test description document (https://github.com/ewasm/tests/issues/40)
- [x] more `create`/`call` tests (https://github.com/ewasm/tests/issues/39)
- [x] more `createFromTransaction` tests (https://github.com/ewasm/tests/pull/35) *@hugo-dc*
- [x] update call test to reflect EEI changes (https://github.com/ewasm/tests/pull/30)
- [x] OOB memory access test cases (https://github.com/ewasm/tests/issues/34, https://github.com/ewasm/tests/pull/52)
- [x] Unreachable in contract creation txn should not create a new account  (https://github.com/ewasm/tests/pull/33)
- [ ] Tests for malformed imports (https://github.com/ewasm/tests/issues/31)
- [ ] Larger values in test cases (https://github.com/ewasm/tests/issues/26)

**Comment by lrettig** [comment]
My update from today: I submitted a raft of PRs with bugfixes to hera and evm2wasm from `stCallCodes`:

- https://github.com/ewasm/hera/pull/250
- https://github.com/ewasm/evm2wasm/pull/280
- https://github.com/ewasm/tests/pull/44

**Comment by lrettig** [comment]
My update from today: This is going well, making good progress. I PRed a bunch of create and call tests last week. They're in the process of being reviewed and merged. Hugo finished and merged his createFromTransaction tests. There are still a few corner cases left to tackle, highlighted in the description here. Will keep working on it this week.

**Comment by axic** [comment]
The list of tests are maintained elsewhere now.
