### ISSUE TITLE
Sprint TODO

### ISSUE THREAD

**Issue by axic** [ewasm/testnet#4]
- [x] Update the EEI design (add Byzantium opcodes) (@axic)
- [ ] Clarify endianness in the EEI design (@axic @chfast)
- [x] Add circleci support to Hera (@chfast)
- [x] Implement all interface methods in Hera (tracked here: https://github.com/ewasm/hera/issues/12) (@jakelang @axic)
- [x] Implement tests for each interface method in testeth (tracked here: https://github.com/ethereum/tests/pull/394) (@hugo-dc @jwasinger @lrettig) (cf. https://github.com/ewasm/tests/issues/11 which is still WIP)
- [x] Add support for EVM-C `set_option` to cpp-ethereum (https://github.com/ethereum/cpp-ethereum/pull/4771) (@chfast)
- [x] Merge heraplus support into cpp-ethereum (https://github.com/ethereum/cpp-ethereum/pull/4766) (@chfast)
- [x] Add fork option in cpp-ethereum to raise the code size limit (`EWASMForkBlock)` (https://github.com/ethereum/cpp-ethereum/pull/4772) (@chast)
- [x] Add codeFromFile genesis option in cpp-ethereum (https://github.com/ethereum/cpp-ethereum/issues/4774) (@chfast)
- [ ] Add debugging via `set_option` to Hera (@chfast)
- [x] Add fallback switching via `set_option` to Hera (https://github.com/ewasm/hera/pull/112) (@axic)
- evm2wasm
  - [ ] pass state tests using evm2wasm (@lrettig, @jwasinger, https://github.com/ewasm/evm2wasm/issues/131, https://gist.github.com/cdetrio/1eb95fe9878b1038978578af0716a818)
  - [ ] evm2wasm C/C++/Rust conversion (@lrettig: https://github.com/lrettig/evm2wasm/, https://github.com/ewasm/evm2wasm/issues/4, https://github.com/ewasm/evm2wasm/pull/153)
  - [ ] Add Byzantium support to evm2wasm (https://github.com/ewasm/evm2wasm/issues/163)
  - [ ] Update gas costs to Byzantium in evm2wasm (https://github.com/ewasm/evm2wasm/issues/164)
  - [ ] Support new call/create EEI methods (https://github.com/ewasm/evm2wasm/issues/184)
  - [x] we need to add an option to Hera to disable interface metering and enable that option when evm2wasm is invoked (https://github.com/ewasm/hera/issues/163)
  - [x] evm2wasm must have an option to insert useGas statements matching the current costs for the opcodes (https://github.com/ewasm/evm2wasm/issues/197)
  - [x] fix `evm2wasm evmtrace` (https://github.com/ewasm/evm2wasm/issues/198)
  - [x] Update wast2wasm to v1 and avoid using wabt in evm2wasm (https://github.com/ewasm/evm2wasm/issues/169)
- [ ] Compile rustbn.js (+ the pairing/mul/add precompile) to webassembly (@cdetrio)
- [x] Add CLI to wasm-metering (javascript) (https://github.com/ewasm/wasm-metering/pull/7) (@axic)
- [x] Include wasm-metering (javascript) in @jwasinger's testeth conversion tool (using https://github.com/ewasm/wasm-metering/pull/7) (@lrettig)
- [x] ~~Add wasm-metering (via javascript exec) directly to testeth~~ (obsoleted)
- [x] Finish and merge wast->wasm converter in testeth (https://github.com/ethereum/cpp-ethereum/pull/4754)  (@axic @chfast)
- [x] Improve debugging in Hera (@axic)
- [x] Add gas deductions for interface methods in Hera (https://github.com/ewasm/hera/issues/74) (@jakelang)
- [x] Check for static flag (for `staticCall`) in interface methods in Hera (@jakelang)
- [ ] Implement keccak256 precompile in cpp-ethereum (https://github.com/ewasm/design/pull/73)
- [ ] Finish EVM-C go-ethereum integration (https://github.com/ethereum/go-ethereum/pull/3410/files) (@chfast)
- [ ] Recompile the Homestead precompile to latest webassembly (@axic)
- [x] Add wasm-metering (via javascript exec) to hera
- [ ] Implement metering in C/C++ (@axic)
- [ ] Rewrite ewasm-cleanup tool in C/C++ (@axic)
- devops
  - [ ] Finish the devops for running nodes (@cdetrio @chfast @jwasinger)
  - [ ] Build a docker image of a client (with [rpcproxy/dopple](https://github.com/ethereum/dopple) for easy testing) (@jwasinger)
- [x] EVM-C: Clarify data and size for empty input in evm_message (@chfast)
- [ ] Set up block explorer (@cdetrio, @lrettig) (https://github.com/ewasm/ewasm-explorer/issues/6)
- [ ] ~~Simple contract deployer frontend~~ (replaced by ewasm-explorer)
- [ ] ~~Write geth eWASM implementation via wagon (https://github.com/go-interpreter/wagon)~~ (tracked in #15)
- [ ] ~~Abstract the VM API in Hera and support wabt~~ (tracked in https://github.com/ewasm/hera/issues/156)
- [ ] ~~... and support wavm~~ (tracked in https://github.com/ewasm/hera/issues/158)
- [ ] Run benchmarks with binaryen/wabt/wavm and potentially in browsers
- [ ] Support dynamic loading of VM in cpp-ethereum (with Boost `shared_library` or http://www.boost.org/doc/libs/master/doc/html/boost_dll.html) (@chfast) (tracked in https://github.com/ewasm/hera/issues/159)

**Comment by jakelang** [comment]
>support wabt
and WAVM

**Comment by lrettig** [comment]
This list is out of date wrt the new testnet sprint and refocusing away from evm2wasm, closing in favor of https://waffle.io/ewasm/testnet/

**Comment by axic** [comment]
Please don't close this until all the tasks from here are migrated off.

**Comment by lrettig** [comment]
Okay, I'll migrate them to individual tasks in waffle now

**Comment by lrettig** [comment]
I migrated all of these tasks to new issues in pm and testnet
